config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  resources :netas do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :edit, :show, :update, :index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :neta
end

app/models/neta.rb
class Neta < ApplicationRecord
  validates :neta_name, presence: true
  validates :source, presence: true
  validates :impression, length: { in: 0..256 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, uniqueness: true, presence: true, length: { maximum: 255 },
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :year_of_experience, length: { maximum: 2 }, numericality: true, allow_nil: true
  before_save { email.downcase! }
  has_secure_password
  has_many :netas, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_netas, through: :favorites, source: :neta
  mount_uploader :image, ImageUploader
  enumerize :sex, in: { undefined: 0, male: 1, female: 2 }, default: :undefined
  enumerize :age, in: { undefined: 00, teens: 10, twenties: 20, thirties: 30, forties: 40, fifties: 50,
    sixties: 60, seventies: 70, eighties: 80 }, default: :undefined
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  add_flash_types :danger
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(neta_id: params[:neta_id])
    redirect_to neta_path(favorite.neta.id), notice: "#{favorite.neta.user.name}さんのネタにいいねしました"
  end

  def destroy
    favorite = current_user.favorites.find_by(neta_id: params[:neta_id]).destroy
    redirect_to neta_path(favorite.neta.id), notice: "#{favorite.neta.user.name}さんのネタへのいいねをはずしました"
  end
end

app/controllers/netas_controller.rb
class NetasController < ApplicationController
  before_action :set_neta, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :edit]

  def new
    if params[:back]
      @neta = Neta.new(neta_params)
    else
      @neta = Neta.new
    end
  end

  def create
    @neta = Neta.create(neta_params)
    @neta.user_id = current_user.id
    if @neta.save
      redirect_to netas_path, notice: 'ネタを記録しました'
    else
      render 'new'
    end
  end

  def confirm
    @neta = Neta.new(neta_params)
    @neta.user_id = current_user.id
    render :new if @neta.invalid?
  end

  def show
    @neta = Neta.find(params[:id])
    if logged_in?
      @favorite = current_user.favorites.find_by(neta_id: @neta.id)
    end
  end

  def edit
    @neta = Neta.find(params[:id])
  end

  def update
    @neta = Neta.find(params[:id])
    if @neta.update(neta_params)
      redirect_to user_path(current_user.id), notice: 'ネタを更新しました'
    else
      render 'edit'
    end
  end

  def index
    @netas = Neta.all
    @search = Neta.ransack(params[:q])
    if params[:q].nil?
      @results = nil
    else
      @results = @search.result
    end
  end

  def destroy
    @neta.destroy
    redirect_to user_path(current_user.id), notice: 'ネタを削除しました'
  end

  private
  def neta_params
    params.require(:neta).permit(:neta_name, :source, :impression)
  end

  def set_neta
    @neta = Neta.find(params[:id])
  end

  def require_login
    unless logged_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = 'ログインしました'
        redirect_to netas_path
      else
        flash[:danger] = 'ログインに失敗しました'
        redirect_to new_session_path
      end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      NetaMailer.neta_mail(@user).deliver
      redirect_to new_session_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id), notice: 'プロフィールを更新しました'
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @netas = @user.netas
    @favorites_netas = @user.favorite_netas
  end

  def index
    @users = User.all
  end

  def destroy
    User.find_by(id: params[:user_id]).destroy
    redirect_to new_user_path, notice: '退会しました'
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation, :image, :sex, :age, :favorite_rakugoka, :year_of_experience)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/netas_helper.rb
module NetasHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_netas_path
    elsif action_name == 'edit'
      neta_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>らくごらいふ</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="css/bootstrap.css" rel="stylesheet">
  </head>
  <body>
    <header>
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse">
                <span class="sr-only">らくごらいふ</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">らくごらいふ</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "あまらくさん", users_path %></li>
                <li><%= link_to "みんなのネタ", netas_path %></li>
              <% if logged_in? %>
                <li><%= link_to "ネタを記録する", new_neta_path %></li>
                <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
              <% else %>
                <li><%= link_to "アカウント登録", new_user_path %></li>
                <li><%= link_to "ログイン", new_session_path %></li>
              <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <div class="container">
      <div class="contents">
        <%= yield %>
      </div>
    </div>
    <footer>
      <div class="footer">
        <p class="copyright text-muted">Copyright &copy; らくごらいふ 2018</p>
      </div>
    </footer>
  </body>
</html>

app/views/netas/_form.html.erb
<% if @neta.errors.any? %>
<div class="field row">
  <div class="col-sm-offset-3 col-sm-6">
    <div id="error_explanation">
      <ul>
        <% @neta.errors.full_messages.each do |msg| %>
          <li class="error-msg"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>
<%= form_with(model: @neta, local: true, url: choose_new_or_edit, class: 'form-horizontal') do |form| %>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <div class="bs-component">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="form-group">
            <div class="col-sm-10 col-sm-offset-1">
              <%= form.label :neta_name %>
            </div>
            <div class="col-sm-10 col-sm-offset-1">
              <%= form.text_field :neta_name, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-10 col-sm-offset-1">
              <%= form.label :source %>
            </div>
            <div class="col-sm-10 col-sm-offset-1">
              <%= form.text_field :source, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-10 col-sm-offset-1">
              <%= form.label :impression %>
            </div>
            <div class="col-sm-10 col-sm-offset-1">
              <%= form.text_area :impression, class: 'form-control', placeholder: 'ネタに取り組んでみての感想を自由にお書きください。' %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-10 col-sm-offset-1">
              <%= form.submit "記録する", class:'btn btn-block btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/netas/confirm.html.erb
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <h4>以下の内容で投稿します</h4>
  </div>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <%= form_with(model: @neta, url: netas_path, local: true) do |form| %>
    <div class="bs-component">
      <div class="panel panel-default">
        <div class="panel-heading">
          演目名
        </div>
        <div class="panel-body">
          <%= @neta.neta_name %>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          参考にした噺家
        </div>
        <div class="panel-body">
          <%= @neta.source %>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          ネタをやってみての感想
        </div>
        <div class="panel-body">
          <%= simple_format(@neta.impression) %>
        </div>
      </div>
    </div>
      <%= form.hidden_field :neta_name %>
      <%= form.hidden_field :source %>
      <%= form.hidden_field :impression %>
      <%= form.submit  "投稿する", class:'btn btn-default btn-primary' %>
    <% end %>
    <%= form_with(model: @neta, url: new_neta_path, local: true, method: 'get') do |form| %>
      <%= form.hidden_field :neta_name %>
      <%= form.hidden_field :source %>
      <%= form.hidden_field :impression %>
      <%= form.submit "もどる", name: 'back', class:'btn btn-default back-btn' %>
    <% end %>
  </div>
</div>

app/views/netas/edit.html.erb
<%= render 'form' %>

app/views/netas/index.html.erb
<div class="row">
  <div class="alert-text">
    <p class="alert-info"><%= notice %></p>
  </div>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <div class="form-group">
    <%= search_form_for @search, url: netas_path do |f| %>
      <%= f.text_field :neta_name_cont, class: 'form-control input_field', placeholder: 'ネタ名で検索' %>
      <%= f.submit "検索", class: 'btn btn-default' %>
    <% end %>
    </div>
  </div>
</div>
<% if @results == nil %>
  <% @netas.each do |neta| %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="user_label">
        <%= link_to image_tag(neta.user.image), user_path(neta.user.id) %>
        <%= link_to neta.user.name, user_path(neta.user.id) %> さん
      </div>
      <div class="bs-component">
        <div class="panel panel-default">
          <div class="panel-body">
            <div>
              <%= link_to neta.neta_name, neta_path(neta.id) %>
            </div>
            <div>
              参考にした噺家：<%= neta.source %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<% else %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      検索結果：<%= @results.size %> 件
    </div>
  </div>
  <% @results.each do |result| %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="user_label">
        <%= link_to image_tag(result.user.image), user_path(result.user.id) %>
        <%= link_to result.user.name, user_path(result.user.id) %> さん
      </div>
      <div class="bs-component">
        <div class="panel panel-default">
          <div class="panel-body">
            <div>
              <%= link_to result.neta_name, neta_path(result.id) %>
            </div>
            <div>
              参考にした噺家：<%= result.source %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/netas/new.html.erb
<%= render 'form' %>

app/views/netas/show.html.erb
<div class="row">
  <div class="alert-text">
    <p class="alert-info"><%= notice %></p>
  </div>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <div class="user_label">
      <%= link_to image_tag(@neta.user.image), user_path(@neta.user.id) %>
      <%= link_to @neta.user.name, user_path(@neta.user.id) %> さん
    </div>
    <div class="bs-component">
      <div class="panel panel-default">
        <div class="panel-heading">
          演目名
        </div>
        <div class="panel-body">
          <%= @neta.neta_name %>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          参考にした噺家
        </div>
        <div class="panel-body">
          <%= @neta.source %>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          ネタをやってみての感想
        </div>
        <div class="panel-body">
          <%= simple_format(@neta.impression) %>
        </div>
      </div>
    </div>
    <% if logged_in? %>
      <% if @neta.user == current_user %>
        <%= link_to "編集", edit_neta_path(@neta.id), class:'btn btn-primary', data: { confirm: '本当に編集していいですか？' } %>
        <%= link_to '削除', neta_path(@neta.id), class:'btn btn-danger', method: :delete, data: { confirm: '本当に削除していいですか？' } %>
      <% else %>
        <% if @favorite.present? %>
            <%= link_to 'いいねをはずす', favorite_path(neta_id: @neta.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'いいね', favorites_path(neta_id: @neta.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tops/index.html.erb
<div class="bs-component">
  <div class="jumbotron">
    <h1>らくごらいふ</h1>
    <p>”らくごらいふ”は</p>
    <p>あまらくさんの</p>
    <p>あまらくさんによる</p>
    <p>あまらくさんのための</p>
    <p>持ちネタ管理サービスです</p>
  </div>
  <div>
    ”らくごらいふ”では、アマチュア落語家のことを”あまらくさん”と呼んでいます。
  </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<div class="field row">
  <div class="col-sm-offset-3 col-sm-6">
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li class="error-msg"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>
<%= form_with(model: @user, local: true, class: 'form-horizontal') do |form| %>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <div class="bs-component">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="title">らくごらいふ プロフィール編集</div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.label :name %>
              </div>
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.text_field :name, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.label :image %>
              </div>
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.file_field :image, id: :feed_image %>
                <%= form.hidden_field :image_cache %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.radio_button :sex, :male %> 男性
                <%= form.radio_button :sex, :female %> 女性
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.label :age %>
              </div>
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.select :age, User.age.options %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.label :year_of_experience %>
              </div>
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.text_field :year_of_experience, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.label :favorite_rakugoka %>
              </div>
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.text_field :favorite_rakugoka, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= form.submit "更新する", class: 'btn btn-block btn-primary' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= link_to "もどる", :back, class:'btn btn-block btn-default' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
<div class="bs-docs-section">
  <% @users.each do |user| %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="bs-component">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= link_to image_tag(user.image), user_path(user.id) %>
            <%= link_to user.name, user_path(user.id) %> さん
            （<%= user.netas.size %>）
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <ul class="row">
        <% @user.errors.full_messages.each do |message| %>
          <li class="error-msg"><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <div class="bs-component">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="title">らくごらいふ アカウント登録</div>
          <%= form_with(model: @user, local: true, class: 'form-horizontal') do |f| %>
          <fieldset>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= f.text_field :name, class: 'form-control', placeholder: '高座名' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= f.email_field :email, class: 'form-control', placeholder: 'メールアドレス' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= f.password_field :password, class: 'form-control', placeholder: 'パスワード' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= f.password_field :password_confirmation, class: 'form-control', placeholder: '確認用パスワード' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-1">
                <%= f.submit "登録する", class:'btn btn-block btn-primary' %>
              </div>
            </div>
          </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <div class="bs-component">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-sm-10 col-sm-offset-1">
            アカウントをお持ちですか？<%= link_to "ログインする", new_session_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="alert-text">
    <p class="alert-info"><%= notice %></p>
  </div>
</div>
<div class="row">
  <div class="col-sm-offset-3 col-sm-6">
    <div class="user_label">
      <%= image_tag @user.image %>
      <%= @user.name %> さん
    </div>
    <table>
      <% if logged_in? %>
        <% if @user.id == current_user.id %>
      <tr>
        <td class="neta-info neta-label">メールアドレス</td>
        <td class="neta-info"><%= @user.email %></td>
      </tr>
        <% end %>
      <% end %>
      <tr>
        <td class="neta-info neta-label">性別</td>
        <td class="neta-info"><%= @user.sex_text %></td>
      </tr>
      <tr>
        <td class="neta-info neta-label">年齢</td>
        <td class="neta-info"><%= @user.age_text %></td>
      </tr>
      <tr>
        <td class="neta-info neta-label">落語歴</td>
        <% if @user.year_of_experience == nil %>
        <td class="neta-info"></td>
        <% else %>
        <td class="neta-info"><%= @user.year_of_experience %> 年</td>
        <% end %>
      </tr>
      <tr>
        <td class="neta-info neta-label">好きな噺家</td>
        <td class="neta-info"><%= @user.favorite_rakugoka %></td>
      </tr>
    </table>
  </div>
</div>
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <% if @user.id == current_user.id %>
      <div>
        <%= link_to "プロフィール編集", edit_user_path(@user.id), class:'btn btn-default', data: { confirm: '本当に編集していいですか？' } %>
        <%= link_to '退会する', user_path(user_id: @user.id), method: :delete, class: 'btn btn-default', data: { confirm: '本当に退会しますか？' } %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>
<div class="neta-list">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div>
        <h4>持ちネタ一覧</h4>
      </div>
    </div>
  </div>
  <% if @netas.size == 0 %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      持ちネタをまだ記録していません。
    </div>
  </div>
  <% end %>
  <% @netas.each do |neta| %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="bs-component">
        <div class="panel panel-default">
          <div class="panel-body">
            <div>
              <%= link_to neta.neta_name, neta_path(neta.id) %>
            </div>
            <div>
              参考にした噺家さん：<%= neta.source %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="fevorite-list">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div>
        <h4>お気に入り一覧</h4>
      </div>
    </div>
  </div>
  <% if @favorites_netas.size == 0 %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      いいねしたネタはまだありません。
    </div>
  </div>
  <% end %>
  <% @favorites_netas.each do |neta| %>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="user_label">
        <%= link_to image_tag(neta.user.image), user_path(neta.user.id) %>
        <%= link_to neta.user.name, user_path(neta.user.id) %> さん
      </div>
      <div class="bs-component">
        <div class="panel panel-default">
          <div class="panel-body">
            <div>
              <%= link_to neta.neta_name, neta_path(neta.id) %>
            </div>
            <div>
              参考にした噺家さん：<%= neta.source %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>